kind: pipeline
name: frontend
steps:
  - name: before-start
    image: node
    commands:
      - npm install --registry=https://registry.npm.taobao.org -g yarn
      - yarn config set registry https://registry.npm.taobao.org
      - yarn --frozen-lockfile --non-interactive
  - name: lint
    image: node
    commands:
      - yarn lint
  - name: test
    image: node
    commands:
      - yarn test
