kind: pipeline
steps:
  - name: before-start
    image: node
    commands:
      - npm install -g yarn
      - yarn --frozen-lockfile --non-interactive
  - name: lint
    image: node
    commands:
      - yarn lint
  - name: test
    image: node
    commands:
      - yarn test
