image: node:current
before_script:
  - npm install --registry=https://registry.npm.taobao.org -g yarn
  - yarn config set registry https://registry.npm.taobao.org
  - yarn --frozen-lockfile --non-interactive

stages:
  - test
  - build

test_job:
  stage: test
  script:
    - yarn lint
    - yarn test

build_job:
  stage: build
  script:
    - yarn build:test
