trigger:
  branches:
    include:
      - master

jobs:
  - job: ubuntu_CI_Tests
    displayName: Ubuntu CI Tests
    pool:
      vmImage: ubuntu-16.04
    strategy:
      matrix:
        node_10_x:
          node_version: 12.x

    steps:
      - script: sudo apt-get update && sudo apt-get install yarn

      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)

      - script: yarn install
        displayName: 'Install Dependency'

      - script: yarn run lint
        displayName: 'Lint Code'

      - script: yarn test
        displayName: 'Run Tests'
